import { Product } from '@/types/product'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const  Home = ({products }: Props) =>  {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
            <h1> Tienda {`Rock{theCode}`}</h1>
            <ul>
              
              {products.map((product) => (
                  <li key={product.id}>
                    <h3>{product.name}</h3>
                    <p>{product.description}</p>
                    <h3>£{product.price}</h3>
                    <Link href={`/products/${product.id}`}>COMPRAR AHORA</Link>
                    </li>
              )
                )}
            </ul>
      </main>
    </>
  )
}
export type Props = {
  products: Product[],
}

export const getServerSideProps: GetServerSideProps = async () => {
 const response: Product[] = await fetch('https://my-json-server.typicode.com/bea-ro/shop-api/products').then((res) => res.json())
  
console.log(response);

  return {
    props:{
      products: response
    },
  }
}

export default Home