import Head from 'next/head'

const getProduct = async () => {
  fetch('api/products/1', {method: 'GET', headers: {
    'Content-Type': 'application/json'
  },
}).then((res) => res.json())
.then((response) => {
  console.log('Respuesta', response)
})
.catch((err) => {
  console.log('Error', err)
})
}



const Home = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1>{`RockThe{Code}`} - Next API Routes</h1>
       <button onClick={getProduct}>GET PRODUCT</button>
      </main>
    </div>
  )
}


export default Home