import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Data } from './api/products/db'
import useSwr from 'swr'

const getProduct = async () => {
  fetch('api/products/1', {method: 'GET', headers: {
    'Content-Type': 'application/json'
  },
}).then((res) => res.json())
.then((response) => {
  console.log('Respuesta', response)
})
.catch((err) => {
  console.log('Error', err)
})
}

const fetchProducts = async(url: string) => {
return fetch(url, {method: 'GET', headers: {
  'Content-Type': 'application/json'
},
}).then((res) => res.json())
}

const Home = () => {
const {data: products, error} = useSwr('api/products', fetchProducts)

console.log('HOME:', {products, error})

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1>{`RockThe{Code}`} - Next API Routes</h1>
       <button onClick={getProduct}>GET PRODUCT</button>
      </main>
    </div>
  )
}


export default Home